#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [2]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [3]:
def transpose(matrix, tr, n): 
    for i in range(n): 
        for j in range(n): 
            tr[i][j] = matrix[j][i] 
    
def isSymmetric(matrix, n): 
      
    tr = [ [0 for j in range(len(matrix[0])) ] for i in range(len(matrix)) ] 
    transpose(matrix, tr, n) 
    for i in range(n): 
        for j in range(n): 
            if (matrix[i][j] != tr[i][j]): 
                return False
    return True


Test your function on the two matrices below

In [4]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [5]:
print(A)

if (isSymmetric(A, 5)): 
    print("Yes")
else: 
    print("No")

[[0.55551603 0.97828298 0.99856221 0.04253979 0.4119049 ]
 [0.12593211 0.44447217 0.38494313 0.86739616 0.44887357]
 [0.5545438  0.72329389 0.34147431 0.06613343 0.69461851]
 [0.78673599 0.51008679 0.66813357 0.03146655 0.45708082]
 [0.99053107 0.08933396 0.80777514 0.45398567 0.24682462]]
No


In [6]:
print(SymMatrix)

if (isSymmetric(SymMatrix, 5)): 
    print("Yes")
else: 
    print("No")

[[0.55551603 0.55210754 0.77655301 0.41463789 0.70121798]
 [0.55210754 0.44447217 0.55411851 0.68874147 0.26910376]
 [0.77655301 0.55411851 0.34147431 0.3671335  0.75119682]
 [0.41463789 0.68874147 0.3671335  0.03146655 0.45553324]
 [0.70121798 0.26910376 0.75119682 0.45553324 0.24682462]]
Yes


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [7]:
def transpose(A,B): 
  
    for i in range(n): 
        for j in range(n): 
            B[i][j] = A[j][i] 
    

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [8]:
#Since A is a 6x6 matrix, n=6
n = 6
A = np.random.rand(6,6)

print(A)

[[0.18130847 0.74274015 0.49688508 0.520588   0.36739837 0.45787911]
 [0.95653967 0.52451803 0.58800904 0.02530077 0.76697686 0.87331898]
 [0.97474988 0.79835231 0.7697217  0.60991839 0.56367213 0.20972266]
 [0.79454861 0.72195449 0.12958759 0.96500108 0.69955061 0.03140319]
 [0.45572135 0.58020394 0.6539642  0.08804996 0.86702362 0.78768489]
 [0.93242727 0.54745948 0.11846465 0.52332619 0.65711927 0.46344024]]


In [9]:
#Let B be a 6x6 zero matrix
B = [[0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0], [0,0,0,0,0,0]]

transpose(A,B) 
print("Transpose of A is") 
for i in range(n): 
    for j in range(n): 
        print(B[i][j], " ", end='') 
    print() 

Transpose of A is
0.18130846855784688  0.9565396747028893  0.9747498797562401  0.7945486105293041  0.4557213498356838  0.9324272655480387  
0.7427401517085741  0.5245180345632497  0.7983523073908555  0.7219544885616952  0.580203943503034  0.5474594815748737  
0.4968850793482842  0.5880090412522458  0.7697216969312926  0.12958759160407818  0.6539641957077632  0.11846464800214496  
0.5205879977152266  0.025300771972190272  0.6099183892737926  0.9650010771336863  0.08804995970182838  0.5233261874975678  
0.36739837025209454  0.7669768585638023  0.5636721345867433  0.699550607064408  0.8670236185951781  0.6571192689598668  
0.4578791101395625  0.8733189787795048  0.20972265777107646  0.03140319275941994  0.7876848851513432  0.46344023559052494  


In [10]:
print(np.transpose(A))

#This gives us same as above 

[[0.18130847 0.95653967 0.97474988 0.79454861 0.45572135 0.93242727]
 [0.74274015 0.52451803 0.79835231 0.72195449 0.58020394 0.54745948]
 [0.49688508 0.58800904 0.7697217  0.12958759 0.6539642  0.11846465]
 [0.520588   0.02530077 0.60991839 0.96500108 0.08804996 0.52332619]
 [0.36739837 0.76697686 0.56367213 0.69955061 0.86702362 0.65711927]
 [0.45787911 0.87331898 0.20972266 0.03140319 0.78768489 0.46344024]]


## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [11]:
import sys 
#For 4x5 matirx n=4 and m=5
N = 4
M = 5
  
# Function to find max element  
def findMax(matrix): 
      
     
    maxElement = -sys.maxsize - 1
   
    #loop to check if each element is greater than the max element
    for i in range(N): 
        for j in range(M): 
            if (matrix[i][j] > maxElement): 
                maxElement = matrix[i][j] 
          
     
    return maxElement 
  

Check your result by comparing to `np.max(A)` for the below random matrix

In [12]:
A = np.random.rand(4,5)

print(np.max(A))

0.9214899488374569


In [13]:
matrix = A 

print(findMax(matrix))

0.9214899488374569


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [14]:
def L1Norm(a):
    i = 0
    j =0
    c = 0
    n=np.shape(a)[1]
    d=np.zeros((n,1))
    while j<np.shape(a)[0]:
        i=0
        while i<np.shape(a)[0]:
            c+=np.abs(a[i,j])
            i+=1
        
        d[j] = c
        j+=1
        c=0
    return max(d)  

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [15]:
A = np.random.rand(3,4)

print(L1Norm(A))

[2.1634272]


In [16]:
print(L1Norm(A))

[2.1634272]


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [17]:
def LinfNorm(a):
    i = 0
    j =0
    c = 0
    n=np.shape(a)[1]
    d=np.zeros((n,1))
    while i<np.shape(a)[0]:
        j=0
        while j<np.shape(a)[0]:
            c+=np.abs(a[i,j])
            j+=1
        
        d[i] = c
        i+=1
        c=0
    return max(d)  

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [18]:
A = np.random.rand(3,4)

la.norm(A,np.inf)

2.325915240060498

In [19]:
LinfNorm(A)

array([1.68722506])

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [20]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [21]:
eigenvaluesA1 = la.eig(A1.T@A1)[0]
lmaxA1 = np.max(eigenvaluesA1)
lmaxA1 = np.min(eigenvaluesA1)
print("Condition number of A1:\t", la.norm(A1,2)*la.norm(la.inv(A1),2))

eigenvaluesA2 = la.eig(A2.T@A2)[0]
lmaxA2 = np.max(eigenvaluesA2)
lmaxA2 = np.min(eigenvaluesA2)
print("Condition number of A2:\t", la.norm(A2,2)*la.norm(la.inv(A2),2))


eigenvaluesA3 = la.eig(A3.T@A3)[0]
lmaxA3 = np.max(eigenvaluesA3)
lmaxA3 = np.min(eigenvaluesA3)
print("Condition number of A3:\t", la.norm(A3,2)*la.norm(la.inv(A3),2))

Condition number of A1:	 21.552466488381857
Condition number of A2:	 13334923332.407896
Condition number of A3:	 15.122449699410629


In [22]:
#The condition numbers of each matrix is quite high so we can say they are all relatively ill-conditioned
#The condition number of a well conditioned matrix is as close to 1 as possible
#However the condtion number of A2 is extremely high compared to that of A1 and A3 and therefore is the most ill-conditioned

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [34]:
b = np.array([1, 2, 3, 4])
db = np.array([0.1 ,0, 0, 0])
nb = b + db
x2 = la.inv(A2)@(b)
dx2 = la.inv(A2)@(nb) - x2
x3 = la.inv(A3)@(b)
dx3 = la.inv(A3)@(nb) - x3

In [35]:
print("Change in b = %.4f%%" %(100*(la.norm(db,2)/la.norm(b,2))))

print("change in x for A2 = %.4f%%" %(100*(la.norm(dx2,2)/la.norm(x2,2))))

print("change in x for A3 = %.4f%%" %(100*(la.norm(dx3,2)/la.norm(x3,2))))

Change in b = 1.8257%
change in x for A2 = 512.6206%
change in x for A3 = 2.1738%


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [10]:
# Answer here
# We can see that the A2 system is way more sensitive to small changes in b
#We could have guessed this from Q3(a) from the high condition number on A2

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [23]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [24]:
eigs = la.eig(A)
print("Eigenvalues = ", eigs[0])

Eigenvalues =  [15.78569318 -2.05164645  1.26595327]


In [25]:
print("Eigenvector 0 = ", eigs[1][:,0])
print("Eigenvector 1 = ", eigs[1][:,1])
print("Eigenvector 2 = ", eigs[1][:,2])

Eigenvector 0 =  [-0.39252008 -0.44424151 -0.80534308]
Eigenvector 1 =  [-0.89589878  0.36255198  0.25675168]
Eigenvector 2 =  [ 0.09818766 -0.77454142  0.6248558 ]


In [26]:
#Eigenvector 0
print(np.dot(A,eigs[1][:,0]))
print(eigs[0][0]*eigs[1][:,0])

[ -6.1962015   -7.01266016 -12.71289871]
[ -6.1962015   -7.01266016 -12.71289871]


In [27]:
#Eigenvector 1
print(np.dot(A,eigs[1][:,1]))
print(eigs[0][1]*eigs[1][:,1])

[ 1.83806756 -0.74382849 -0.52676368]
[ 1.83806756 -0.74382849 -0.52676368]


In [28]:
#Eigenvector 2
print(np.dot(A,eigs[1][:,2]))
print(eigs[0][2]*eigs[1][:,2])

[ 0.12430099 -0.98053324  0.79103825]
[ 0.12430099 -0.98053324  0.79103825]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [29]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [53]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`

In [31]:
print(la.eig(A))

(array([4.91480442, 0.85058153, 0.14281707, 0.21512836]), array([[ 0.59947641,  0.30724064, -0.63319959, -0.3811686 ],
       [ 0.33318806, -0.3894447 ,  0.53214542, -0.67389895],
       [ 0.49528112,  0.58292464,  0.54707607,  0.34000478],
       [ 0.53320761, -0.64353313, -0.12879172,  0.53382343]]))
